author:
  gender: Mr
  name: Martin
  firstname: QUINSON
  field: Computer Science
  title: Director of the Computer Sciences teaching department

student:
  gender: Mr
  name: Jean
  firstname: DUPONT
  pronoun: he
  dob: 26th of August 2000
  pob: Rennes (FRANCE)
  schoolyear: "2023-2024"
  yearname: First year of Master's degree in Computer Science
