author:
  gender: Mr
  name: Martin
  firstname: QUINSON
  field: Computer Science
  title: Director of the Computer Sciences teaching department

student:
  gender: Mrs
  name: Jean
  firstname: DUPONT
  pronoun: he
  dob: 15th of August 2001
  pob: Toulouse (FRANCE)
  schoolyear: "2021-2022"
  yearname: 1st year of Master's degree in Computer Science
