author:
  gender: Mr
  name: Martin
  firstname: QUINSON
  field: Computer Science
  title: Head of Studies of the Department of Computer Sciences

student:
  gender: Mrs
  name: Emma
  firstname: REDOR
  pronoun: she
  dob: 26th of September 2001
  pob: Saint-Nazaire (FRANCE)
  schoolyear: "2021-2022"
  yearname: 3rd year of Bachelor's degree in Computer Science
